suppliers:
  - https://api.myjson.com/bins/gdmqa
  - https://api.myjson.com/bins/1fva3m
  - https://api.myjson.com/bins/j6kzm
  - https://api.myjson.com/bins/fq5iu
  - https://api.myjson.com/bins/101192
